### ISSUE TITLE
[1.18.2] Crash on World Creation

### ISSUE THREAD

**Issue by gamenTV** [McJty/RFToolsDimensions#398]
Issue description: Server Crashed on Server Creation

Versions:
* Minecraft: 1.18.2
* Forge: 1.18.2-40.1.0
* McJtyLib: 1.18-6.0.13
* RFTools: 1.18-3.0.7
* RFTools Dimensions: 1.18-8.0.4

[crash-2022-05-18_21.08.30-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/8727527/crash-2022-05-18_21.08.30-server.txt)

**Comment by McJty** [comment]
Can you give more information? What dimlets did you use? Can you sneak right click with the dimension tab in your hand and tell me what that says?

**Comment by gamenTV** [comment]
![image](https://user-images.githubusercontent.com/50620722/169357177-63d84782-305e-42f3-b767-a176acbb9d3b.png)

- Attribute
  - nooceans
  - cities
- Structure
  - swamp_hut
  - monument
  - shipwreck
  - desert_pyramid
  - stronghold
  - fortress
  - mineshaft
- Terrain
  - flat
- Sky
  - noclouds
- Biome Category
  - extreme_hills

**Comment by rickyelopez** [comment]
I also had this happen on world creation in the latest Direwolf20 1.18.2 pack. I made an empty dim, no dimlets. Seems like the dim works fine after the server restarts, though?

**Comment by Hachuurui** [comment]
I'm dealing with a similar crash but a different cause. Generating a random dimension causes a full server crash with the below crash report. 
This is with the TNP Limitless 5 Pack. 
[crash-2022-05-25_21.08.46-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/8775499/crash-2022-05-25_21.08.46-server.txt)
update:
reloading the server the dim works as stated above, except it doesn't have a receiver and one has to be added to the dim.

**Comment by McJty** [comment]
I fixed some of the reports in this list. There was an accidental dependency on Lost Cities. Not sure if this is also the problem in the first report on this issue though

**Comment by Hachuurui** [comment]
> I fixed some of the reports in this list. There was an accidental dependency on Lost Cities. Not sure if this is also the problem in the first report on this issue though

I have a server setup locally for testing the update to tnp. If you would like me to test a build on this, let me know and I'll swap the jars out. Just toss me a build link.

**Comment by McJty** [comment]
It's on CurseForge

**Comment by Hachuurui** [comment]
> It's on CurseForge

multiple dimensions created and entered. no issues. this appears to have fixed the issue for me at least.
Thanks again for all the work you do mate!

**Comment by gamenTV** [comment]
Could finally test it :) unfortunately it still crashes on me :(
[crash-2022-05-28_20.57.22-server.txt](https://github.com/McJtyMods/RFToolsDimensions/files/8791680/crash-2022-05-28_20.57.22-server.txt)

**Comment by McJty** [comment]
Did you have Lost Cities in your modlist for a time? Because somehow you got a dimension with the Lost Cities dimlet in it and that's only possible if Lost Cities was present at some point

**Comment by gamenTV** [comment]
From which mod is the Lost Cities?

**Comment by McJty** [comment]
From the mod called 'Lost Cities'

**Comment by gamenTV** [comment]
Well than i never had installed that 😄

**Comment by McJty** [comment]
Can you describe exactly what you are doing and when this crash occurs?

**Comment by gamenTV** [comment]
Well i create the Dimension with some Dimlets and load that. The server only crashes when I use the Lost Cities dimlet. Probably because I don't have the mod installed. Questionable only where I have the dimlet if it should not be available.

**Comment by McJty** [comment]
Well ... I don't know how you got that lost cities dimlet but obviously don't use that.

**Comment by gamenTV** [comment]
Yeah. Probably i find out where i get that.

**Comment by McJty** [comment]
Next version will contain an additional safety so that even in the case where you get a lost city dimlet without lost cities it will not crash
